core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('', include('educamy.urls', namespace='educamy')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

educamy/urls.py
from django.urls import path
from .views import loginView, registerView, userProfile, changePassword, DashboardView, generateContent, logoutApp, ItinerariesView, SchoolSubjectsView, SchoolSubjectEditView, SchoolSubjectDeleteView, MicroPlanDeleteView, AnnualPlanDeleteView, AnnualItinerarieDetailView, MicroItinerarieDetailView, deleteAnnualQuiz, deleteMicroQuiz, deletePptxFileMicro, deletePptxFileAnnual

app_name = 'educamy'

urlpatterns = [
    path('', loginView, name='login'),
    path('register/', registerView, name='register'),
    path('logout/', logoutApp, name='logout'),
    path('profile/<int:pk>/', userProfile, name='profile'),
    path('profile/password/', changePassword, name='change_password'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('school_subjects/', SchoolSubjectsView.as_view(), name='school_subjects'),
    path('school_subjects/edit/<int:pk>/', SchoolSubjectEditView.as_view(), name='edit_school_subject'),
    path('school_subjects/delete/<int:pk>/', SchoolSubjectDeleteView.as_view(), name='delete_school_subject'),
    path('itineraries/', ItinerariesView.as_view(), name='itineraries'),
    path('itineraries/generate_content/', generateContent, name='generate_content'),
    path('itineraries/annual/<int:pk>/delete/', AnnualPlanDeleteView.as_view(), name='delete_annual_plan'),
    path('itineraries/annual/<int:pk>/detail', AnnualItinerarieDetailView.as_view(), name='detail_annual_plan'),
    path('itineraries/micro/<int:pk>/detail', MicroItinerarieDetailView.as_view(), name='detail_micro_plan'),
    path('itineraries/micro/<int:pk>/delete/', MicroPlanDeleteView.as_view(), name='delete_micro_plan'),


    path('quiz/delete_annual/<int:quiz_id>/', deleteAnnualQuiz, name='delete_quiz'),
    path('quiz/delete_micro/<int:quiz_id>/', deleteMicroQuiz, name='delete_quiz'),
    path('pptx/delete_micro/<int:pk>/', deletePptxFileMicro, name='delete_pptx_micro'),
    path('pptx/delete_annual/<int:pk>/', deletePptxFileAnnual, name='delete_pptx_annual'),

    

    


]

educamy/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib import messages
from django.utils.translation import activate
from .forms import CreateUser
from django.views.generic import View
from dotenv import load_dotenv
import os
import tempfile
from weasyprint import HTML
import google.generativeai as genai
from bs4 import BeautifulSoup
from datetime import timedelta
from django.contrib.auth.decorators import login_required
from .models import GeneratedContent, SchoolSubject, MicroPlan, AnualPlan, Quiz, Profile, PptxFile
from .forms import itinerarieForm, AddSchoolSubjectForm, UpdateProfile
from django.shortcuts import get_object_or_404
from math import ceil
from django.contrib.auth.models import User
import json
# Cargar variables de entorno
load_dotenv()
from educamy.services.genai import GENAI_API_KEY, model
from django.utils.decorators import method_decorator
import qrcode
import base64
from io import BytesIO
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.decorators import login_required
from educamy.services.slidespeak import headers
from django.core.files.temp import NamedTemporaryFile
import requests
import datetime
from django.core.files.base import ContentFile
import time
from django.contrib.auth import get_user_model
from django.db.models import Q









# Registro de usuarios

def registerView(request):
    activate('es')
    if request.method == 'POST':
        form = CreateUser(request.POST)
        if form.is_valid():
            form.save()
            return redirect('educamy:login')
    else: 
        form = CreateUser()
    return render(request, 'register.html', {'formulario': form})


def loginView(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username= username, password=password)
            if user is not None:
                login(request, user)
                # messages.success(request, f'Bienvenido {username}')
                return redirect('educamy:dashboard')
            else:
                messages.error(request, 'Usuario o contraseña incorrectos')
        else:
            messages.error(request, 'Usuario o contraseña incorrectos')


    form = AuthenticationForm()   

    form.fields['username'].label = 'Nombre de usuario'
    form.fields['password'].label = 'Contraseña'
    return render(request, 'login.html', {"form": form})


def logoutApp(request):
    logout(request)
    return redirect('educamy:login')




@login_required
def userProfile(request, pk):
    activate('es')

    if request.user.pk != pk:
        # messages.error(request, "No tienes permiso para ver este perfil.")
        return redirect('educamy:dashboard')


    user = get_object_or_404(User, pk=pk)
    
    if request.method == 'POST':
        form = UpdateProfile(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('educamy:profile', pk=request.user.pk)
    else:
        form = UpdateProfile(instance=request.user)



    annualItineraries = AnualPlan.objects.filter(generatedContentId__user=request.user).order_by('-created_at')
    microItineraries = MicroPlan.objects.filter(generatedContentId__user=request.user).order_by('-created_at')



    pptxAnnualGenerated = PptxFile.objects.filter(anual_plan__generatedContentId__user=request.user).order_by('-created_at')
    print("pptxGenerated", pptxAnnualGenerated)
    pptxMicroGenerated = PptxFile.objects.filter(micro_plan__generatedContentId__user=request.user).order_by('-created_at')
    print("pptxMicroGenerated", pptxMicroGenerated)
    pptxCount = pptxAnnualGenerated.count()
    pptxCount += pptxMicroGenerated.count()


    itinerariesCount = annualItineraries.count()
    itinerariesCount += microItineraries.count()


    context = {
        'user': user,
        'form': form,
        'user_photo': request.user.profile.photo.url if request.user.profile.photo else None,
        'itinerariesCount': itinerariesCount,
        'pptxCount': pptxCount,
        

        
    }
    return render(request, 'profile.html', context)



def changePassword(request):
    activate('es')
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            
            # Actualizamos la sesión para que no se cierre al cambiar la contraseña
            update_session_auth_hash(request, form.user)
            
            # Redirigimos a la página del perfil del usuario
            return redirect('educamy:profile', pk=request.user.pk)  # Pasamos el pk del usuario
    else:
        form = PasswordChangeForm(request.user) 

    return render(request, 'changePassword.html', {'form': form})





# Crear un perfil por cada usuario creado
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)    


# Guardar el perfil creado
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()










@method_decorator(login_required, name='dispatch')
class DashboardView(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_superuser:
            users = User.objects.all()
            user_stats = []
            for user in users:
                annual_count = AnualPlan.objects.filter(generatedContentId__user=user).count()
                micro_count = MicroPlan.objects.filter(generatedContentId__user=user).count()
                itineraries_count = annual_count + micro_count
                pptx_count = PptxFile.objects.filter(
                    Q(anual_plan__generatedContentId__user=user) |
                    Q(micro_plan__generatedContentId__user=user)
                ).count()
                user_stats.append({
                    'user': user,
                    'itineraries_count': itineraries_count,
                    'pptx_count': pptx_count,
                })

            context = {
                'users': users,
                'user_stats': user_stats,
                'usersCount': users.count(),
                'itinerariesCount': AnualPlan.objects.count() + MicroPlan.objects.count(),
                'pptxCount': PptxFile.objects.count(),
            }
            return render(request, 'adminDashboard.html', context)
        else:
            
            
            annualItineraries = AnualPlan.objects.filter(generatedContentId__user=request.user).order_by('-created_at')
            microItineraries = MicroPlan.objects.filter(generatedContentId__user=request.user).order_by('-created_at')



            pptxAnnualGenerated = PptxFile.objects.filter(anual_plan__generatedContentId__user=request.user).order_by('-created_at')
            print("pptxGenerated", pptxAnnualGenerated)
            pptxMicroGenerated = PptxFile.objects.filter(micro_plan__generatedContentId__user=request.user).order_by('-created_at')
            print("pptxMicroGenerated", pptxMicroGenerated)
            pptxCount = pptxAnnualGenerated.count()
            pptxCount += pptxMicroGenerated.count()


            itinerariesCount = annualItineraries.count()
            itinerariesCount += microItineraries.count()
            context = {
                'user': request.user,
                'annualItineraries': annualItineraries,
                'microItineraries': microItineraries,
                'itinerariesCount': itinerariesCount,
                'pptxCount': pptxCount,
            }
            return render(request, 'dashboard.html', context)
        
    def post(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            return redirect('educamy:dashboard')

        # Obtiene el ID del usuario a eliminar del formulario
        user_id = request.POST.get('user_id')
        User = get_user_model()

        try:
            user_to_delete = User.objects.get(pk=user_id)
        
            # if user_to_delete.is_superuser or user_to_delete == request.user:
            #     print("Intento de eliminar al superusuario principal o a sí mismo.")

            if user_to_delete == request.user:
                print("Intento de eliminar a sí mismo.")
            else:
                user_to_delete.delete()
                print("Usuario eliminado correctamente.")
        except User.DoesNotExist:
            print("Usuario no encontrado.")

        return redirect('educamy:dashboard')
        



    

@method_decorator(login_required, name='dispatch')
class ItinerariesView(View):
    def get(self, request, *args, **kwargs):
        annualItineraries = AnualPlan.objects.filter(generatedContentId__user=request.user).order_by('-created_at')
        microItineraries = MicroPlan.objects.filter(generatedContentId__user=request.user).order_by('-created_at')
        itinerariesCount = annualItineraries.count()
        itinerariesCount += microItineraries.count()
     

        for micro in microItineraries:
            print("temas", micro.topic)
     
        context = {
                'user': request.user,
                'annualItineraries': annualItineraries,
                'microItineraries': microItineraries,
                'itinerariesCount': itinerariesCount,
        }
        return render(request, 'itineraries.html', context)
    
@method_decorator(login_required, name='dispatch')
class AnnualPlanDeleteView(View):
    def post(self, request, pk):
        annualItineraries = get_object_or_404(AnualPlan, pk=pk, generatedContentId__user=request.user)

educamy/templates/base.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&display=swap" rel="stylesheet" />
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
    {% block metatag %}

    {% endblock %}
    {% tailwind_css %}
  </head>
  <body>
    {% block content %}

    {% endblock %}
  </body>
</html>

<style>
  body {
    font-family: 'Lexend', sans-serif;
  }
  

</style>

educamy/templates/changePassword.html
{% extends "layout.html" %}
{% load tailwind_filters %}

{% block dashboardContent %}
    <form method="post">
        <h1 class="font-bold text-2xl mb-2">Cambiar Contraseña</h1>
        {% csrf_token %}
        {{ form | crispy }}
        <div  class="flex justify-end w-full">
            <button class="bg-purple-900 text-white px-2 py-2 rounded-md mt-4" type="submit">Cambiar contraseña</button>
        </div>
    </form>



{% endblock dashboardContent %}

educamy/templates/dashboard.html
{% extends 'layout.html' %}

{% block dashboardContent %}
<div class="flex flex-wrap justify-between items-center mb-4 w-full">
    <div class="lg:w-[50%] w-full">
        <h2 class="text-3xl font-bold">Bienvenido
        <span class="text-purple-900">
            {{ user }}
        </span>
        !
        </h2>
        <h6 class="text-sm ">
            Crea y gestiona tus itinerarios de clase con ayuda de
            <span class="text-orange-900 font-bold">IA</span>
        </h6>
    </div>

    <div class="lg:w-[50%] w-full flex justify-end">
        <a class="text-sm bg-purple-900 text-white px-4 rounded-md py-2"
                href="{% url 'educamy:generate_content' %}">Generar Itinerario
        <a>
    </div>

</div>

{% comment %} Dashboard Resumen {% endcomment %}
<section class="grid lg:grid-cols-3 grid-cols-2 gap-4">
    {% comment %} Itinerarios {% endcomment %}
    <div
        class="border-1 border-gray-300 rounded-lg p-4 bg-white shadow-md flex flex-col items-start justify-center w-full">
        <div class="flex justify-between w-full">
            <h3 class="text-sm font-semibold">Total itinerarios</h3>
            <svg class="text-purple-900" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="lucide lucide-file-spreadsheet-icon lucide-file-spreadsheet">
                <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
                <path d="M14 2v4a2 2 0 0 0 2 2h4" />
                <path d="M8 13h2" />
                <path d="M14 13h2" />
                <path d="M8 17h2" />
                <path d="M14 17h2" />
            </svg>
        </div>
        <h4 class="font-bold text-2xl">
            {{ itinerariesCount }}
        </h4>
        <p class="text-xs opacity-75">Número de itinearios generados</p>
    </div>
    {% comment %} Asignaturas {% endcomment %}
    <div
        class="border-1 border-gray-300 rounded-lg p-4 bg-white shadow-md flex flex-col items-start justify-center w-full">
        <div class="flex justify-between w-full">
            <h3 class="text-sm font-semibold">Diapositivas</h3>
            <svg class="text-orange-800" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="lucide lucide-book-open-icon lucide-book-open">
                <path d="M12 7v14" />
                <path
                    d="M3 18a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h5a4 4 0 0 1 4 4 4 4 0 0 1 4-4h5a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1h-6a3 3 0 0 0-3 3 3 3 0 0 0-3-3z" />
            </svg>
        </div>
        <h4 class="font-bold text-2xl">
            {{pptxCount}}
        </h4>
        <p class="text-xs opacity-75">Número de diapostivas generadas</p>
    </div>
    {% comment %} Estudiantes {% endcomment %}
    {% comment %} <div
        class="border-1 border-gray-300 rounded-lg p-4 bg-white shadow-md flex flex-col items-start justify-center w-full">
        <div class="flex justify-between w-full">
            <h3 class="text-sm font-semibold">Estudiantes</h3>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="lucide lucide-users-round-icon lucide-users-round">
                <path d="M18 21a8 8 0 0 0-16 0" />
                <circle cx="10" cy="8" r="5" />
                <path d="M22 20c0-3.37-2-6.5-4-8a5 5 0 0 0-.45-8.3" />
            </svg>
        </div>
        <h4 class="font-bold text-2xl">
            8
        </h4>
        <p class="text-xs opacity-75">Description</p>
    </div> {% endcomment %}
</section>



<section class="mt-4">
    <div class="flex justify-between items-center">
        <h2 class="text-xl font-bold ">Mis Itinerarios</h2>
        <div class="flex gap-4 items-center">
            
            <a class="text-xs opacity-75" href="{% url 'educamy:itineraries' %}">
                Ver Todos
            </a> 
        </div>
    </div>


    <div class="flex gap-4 mb-4 mt-2">
        <button id="microItinerariesBtn" class="bg-green-600 rounded-md px-4 py-2 cursor-pointer text-xs font-semibold">
            Microcurriculares
        </button>
        <button id="annualItinerariesBtn" class="bg-green-600 rounded-md px-4 py-2 cursor-pointer text-xs font-semibold">
            Anuales
        </button>
    </div>



    <div id="microItineraries">
        <h3 class="text-sm opacity-75 mb-4">Registros de itinerarios Microcurriculares generados</h3>
        <div class="grid lg:grid-cols-3 gap-4 grid-cols-1 mt-2" >     
            {% for itinerarie in microItineraries %}
            <div
                class="border-1  border-gray-300 rounded-lg p-4 bg-white shadow-md flex flex-col items-start justify-center w-full h-fit">
                <div class="flex flex-col justify-center w-full">
                    <div class="flex justify-between items-center w-full mb-2">
                        <h3 class="text-md font-bold">Itinerario de {{itinerarie.school_subject}}</h3>
                        
                        <a  href="{{itinerarie.pdf_file.url}}"
                            download="{{itinerarie.school_subject}}_itinerario.pdf"
                            class="cursor-pointer">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="orange" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-file-down-icon lucide-file-down"><path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/><path d="M12 18v-6"/><path d="m9 15 3 3 3-3"/></svg>
                        </a>
                        
                    </div>
                    <div class="flex gap-2 items-center opacity-75">
                        <svg xmlns="http://www.w3.org/2000/svg" width="15" height="24" viewBox="0 0 24 24" fill="none"
                            stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                            class="lucide lucide-book-icon lucide-book">
                            <path
                                d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H19a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1H6.5a1 1 0 0 1 0-5H20" />
                        </svg>
                        <h5 class="text-sm">{{itinerarie.school_subject}}</h5>
                    </div>
                    <div class="flex gap-2 items-center opacity-75">
                        <svg xmlns="http://www.w3.org/2000/svg" width="15" height="24" viewBox="0 0 24 24" fill="none"
                            stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                            class="lucide lucide-calendar-icon lucide-calendar">
                            <path d="M8 2v4" />
                            <path d="M16 2v4" />
                            <rect width="18" height="18" x="3" y="4" rx="2" />
                            <path d="M3 10h18" />
                        </svg>
                        <h5 class="text-sm">{{itinerarie.start_date}} - {{itinerarie.end_date}}</h5>
                    </div>
                    <div>
                        <h5 class="text-sm font-semibold mt-2">Objetivos:</h5>
                        
                        {% for objetives in itinerarie.goals  %}
                            {% for objetive in objetives  %}
                                <p class="text-sm opacity-75 flex gap-2">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-goal-icon lucide-goal"><path d="M12 13V2l8 4-8 4"/><path d="M20.561 10.222a9 9 0 1 1-12.55-5.29"/><path d="M8.002 9.997a5 5 0 1 0 8.9 2.02"/></svg>
                                    {{objetive}}
                                </p>
                            {% endfor %}
                        {% endfor %}
                    </div>
                    <a class="w-full text-sm text-center mt-2 bg-green-600 py-1 rounded-md" 
                    href="{% url "educamy:detail_micro_plan" itinerarie.pk %}">Ver Detalles
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>


    <div id="annualItineraries" class="hidden">
        <h3 class="text-sm opacity-75 mb-4">Registros de itinerarios Anuales generados</h3>
        <div class="grid lg:grid-cols-3 gap-4 grid-cols-1 mt-2">
            {% for itinerarie in annualItineraries %}
            <div
                class="border-1 h-fit border-gray-300 rounded-lg p-4 bg-white shadow-md flex flex-col items-start justify-center w-full">
                <div class="flex flex-col justify-center w-full">
                    <div class="flex justify-between items-center w-full mb-2">
                        <h3 class="text-md font-bold">Itinerario de {{itinerarie.school_subject}}</h3>
                        <a href="{{itinerarie.pdf_file.url}}"
                            download="{{itinerarie.school_subject}}_itinerario.pdf"
                            
                            class="cursor-pointer">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="orange" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-file-down-icon lucide-file-down"><path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/><path d="M12 18v-6"/><path d="m9 15 3 3 3-3"/></svg>
                        </a>
                    </div>
                    <div class="flex gap-2 items-center opacity-75">
                        <svg xmlns="http://www.w3.org/2000/svg" width="15" height="24" viewBox="0 0 24 24" fill="none"
                            stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                            class="lucide lucide-book-icon lucide-book">
                            <path
                                d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H19a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1H6.5a1 1 0 0 1 0-5H20" />
                        </svg>
                        <h5 class="text-sm">{{itinerarie.school_subject}}</h5>
                    </div>
                    <div class="flex gap-2 items-center opacity-75">
                        <svg xmlns="http://www.w3.org/2000/svg" width="15" height="24" viewBox="0 0 24 24" fill="none"
                            stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                            class="lucide lucide-calendar-icon lucide-calendar">
                            <path d="M8 2v4" />
                            <path d="M16 2v4" />
                            <rect width="18" height="18" x="3" y="4" rx="2" />
                            <path d="M3 10h18" />
                        </svg>
                        <h5 class="text-sm">{{itinerarie.start_date}} - {{itinerarie.end_date}}</h5>
                    </div>

                    <div>
                        <h5 class="text-sm font-semibold mt-2">Metodologias:</h5>
                        
                        {% for methodologies in itinerarie.methodologies|slice:':1'  %}
                            {% for method in methodologies  %}
                                <p class="text-sm opacity-75 flex gap-2">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-flask-conical-icon lucide-flask-conical"><path d="M14 2v6a2 2 0 0 0 .245.96l5.51 10.08A2 2 0 0 1 18 22H6a2 2 0 0 1-1.755-2.96l5.51-10.08A2 2 0 0 0 10 8V2"/><path d="M6.453 15h11.094"/><path d="M8.5 2h7"/></svg>
                                    {{method}}
                                </p>
                            {% endfor %}
                        {% endfor %}
                    </div>
                    <a class="w-full text-sm text-center mt-2 bg-green-600 py-1 rounded-md" 
                    href="{% url "educamy:detail_annual_plan" itinerarie.pk %}">Ver Detalles
                    </a>
                </div>
            </div>
            {% endfor %}





        </div>
    </div>


    <script>
        const microItinerariesBtn  = document.getElementById('microItinerariesBtn');
        const annualItinerariesBtn = document.getElementById('annualItinerariesBtn');
        const microSection         = document.getElementById('microItineraries');
        const annualSection        = document.getElementById('annualItineraries');

        microItinerariesBtn.addEventListener('click', () => {
            microSection.classList.remove('hidden');
            annualSection.classList.add('hidden');
        });

        annualItinerariesBtn.addEventListener('click', () => {
            annualSection.classList.remove('hidden');
            microSection.classList.add('hidden');
        });
    </script>
</section>




{% endblock %}

educamy/templates/login.html
{% extends 'base.html' %}



{% load static %}
{% load tailwind_filters %}



{% block content %}
  <section class="w-full mx-auto grid grid-cols-1 h-screen overflow-hidden relative bg-gradient-to-br from-purple-50 via-purple-100 to-purple-700 ">
    <div class="flex flex-col items-center justify-center z-10">

        <img class="relative w-full h-10 mb-10" src="{% static 'educamy.svg' %}" alt="logo">
   
      <h2 class="mb-5 text-black font-bold text-2xl tracking-tighter">Inicia Sesión</h2>
      <p class="text-black text-sm text-center">
        Sistema de generación de Itinerarios para 
        <hr/>
        <span class="font-bold">
          Docentes
        </span>
      
      </p>

      <form class="min-w-[280px] mt-4 lg:min-w-[400px] z-20 " method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form |crispy }}
        <button class="bg-purple-700 mt-4 border-2 border-purple-700 text-white hover:bg-purple-900 hover:text-white text-base hover:border-purple-900 rounded-lg py-2.5 px-5 transition-colors w-full text-md">Entrar</button>
      </form>
      {% if messages %}
        {% for message in messages %}
          <div class="bg-red-100 text-red-800 px-4 py-2 rounded mb-4">
              {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <div class="z-20">
        <p class="text-center mt-3 text-[14px]">
          No tienes una cuenta aun?
          <a href="{% url 'educamy:register' %}" class="text-purple-700 hover:underline">Crea una Ahora!</a>
        </p>
      </div>
    </div>
  </section>
{% endblock %}